switchmap:
  build: build/switchmap/
  log_driver: "syslog"
  log_opt:
    tag: "switchmap"
  #restart: always
  #cap_add:
  #  - NET_BIND_SERVICE
  #volumes:
  #  - ./fluentd/logs:/fluentd/log
  #  - ./fluentd/conf:/fluentd/etc
  ports:
    - "8080:80/tcp"
    - "4434:443/tcp"
  #links:
  #  - elasticsearch
