switchmap:
  build: build/switchmap/
  log_driver: "syslog"
  log_opt:
    tag: "switchmap"
  restart: always
  volumes:
    - ./switchmap/conf:/configs
  ports:
    - "8080:80/tcp"
    - "4434:443/tcp"
